spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geo_demo?serverTimezone=Asia/Shanghai
    username: root
    password: 123456zw


server:
  port: 8080
logging:
  level:
    root: info
    org.springframework.jdbc: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: false


